# Generated by Django 6.0.7 on 2026-08-03 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('health', 'Sức khỏe'), ('fitness', 'Thể hình'), ('study', 'Học tập'), ('personal', 'Cá nhân'), ('other', 'Khác')], default='other', max_length=30)),
                ('frequency', models.CharField(choices=[('daily', 'Hằng ngày'), ('weekly', 'Hằng tuần'), ('monthly', 'Hằng tháng')], default='daily', max_length=20)),
                ('target_value', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('unit', models.CharField(default='lần', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thói quen',
                'verbose_name_plural': 'Thói quen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Chưa hoàn thành'), ('completed', 'Hoàn thành'), ('skipped', 'Bỏ qua')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='habits.habit')),
            ],
            options={
                'verbose_name': 'Nhật ký thói quen',
                'verbose_name_plural': 'Nhật ký thói quen',
                'ordering': ['-date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('habit', 'date'), name='unique_habit_log_per_day')],
            },
        ),
    ]
