# Generated by Django 6.0.7 on 2026-08-04 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('top', 'Áo'), ('bottom', 'Quần'), ('shoes', 'Giày'), ('outerwear', 'Áo khoác'), ('accessory', 'Phụ kiện')], max_length=20)),
                ('color', models.CharField(max_length=100)),
                ('season', models.CharField(choices=[('spring', 'Mùa xuân'), ('summer', 'Mùa hè'), ('autumn', 'Mùa thu'), ('winter', 'Mùa đông'), ('all_season', 'Quanh năm')], default='all_season', max_length=20)),
                ('occasion', models.CharField(choices=[('casual', 'Hằng ngày'), ('work', 'Đi làm'), ('sport', 'Thể thao'), ('party', 'Tiệc'), ('formal', 'Trang trọng'), ('versatile', 'Đa dụng')], default='versatile', max_length=20)),
                ('image', models.ImageField(upload_to='wardrobe/')),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trang phục',
                'verbose_name_plural': 'Trang phục',
                'ordering': ['-created_at'],
            },
        ),
    ]
