# Generated by Django 6.0.7 on 2026-08-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
