# Generated by Django 6.0.7 on 2026-08-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0002_clothingitem_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='color',
            field=models.CharField(choices=[('white', 'Trắng'), ('black', 'Đen'), ('gray', 'Xám'), ('blue', 'Xanh dương'), ('green', 'Xanh lá'), ('red', 'Đỏ'), ('yellow', 'Vàng'), ('orange', 'Cam'), ('pink', 'Hồng'), ('purple', 'Tím'), ('brown', 'Nâu'), ('beige', 'Be')], max_length=100),
        ),
    ]
