# Generated by Django 6.0.7 on 2026-07-24 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=225)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('study', 'Học tập'), ('health', 'Sức khỏe'), ('fitness', 'Thể hình'), ('career', 'Sự nghiệp'), ('finance', 'Tài chính'), ('relationship', 'Mối quan hệ'), ('personal_development', 'Phát triển bản thân'), ('other', 'Khác')], default='other', max_length=50)),
                ('priority', models.CharField(choices=[('pending', 'Chưa bắt đầu'), ('in_progress', 'Đang thực hiện'), ('paused', 'Tạm dừng'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Chưa bắt đầu'), ('in_progress', 'Đang thực hiện'), ('paused', 'Tạm dừng'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mục tiêu',
                'verbose_name_plural': 'Mục tiêu',
                'ordering': ['-created_at'],
            },
        ),
    ]
