# Generated by Django 6.0.7 on 2026-07-27 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_milestone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Chưa bắt đầu'), ('in_progress', 'Đang thực hiện'), ('completed', 'Hoàn thành'), ('skipped', 'Đã bỏ qua')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao')], default='medium', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('estimated_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('difficulty_feedback', models.CharField(blank=True, choices=[('very_easy', 'Rất dễ'), ('easy', 'Dễ'), ('normal', 'Vừa sức'), ('hard', 'Khó'), ('very_hard', 'Rất khó')], max_length=20, null=True)),
                ('feedback_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='goals.milestone')),
            ],
            options={
                'verbose_name': 'Nhiệm vụ',
                'verbose_name_plural': 'Các nhiệm vụ',
                'ordering': ['order', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('milestone', 'order'), name='unique_task_order_per_milestone')],
            },
        ),
    ]
