# Generated by Django 6.0.7 on 2026-07-27 09:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ai_feedback', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_history', to='goals.goal')),
            ],
            options={
                'verbose_name': 'Tiến độ mục tiêu',
                'verbose_name_plural': 'Lịch sử tiến độ mục tiêu',
                'ordering': ['-recorded_at', '-created_at'],
            },
        ),
    ]
