# Generated by Django 6.0.7 on 2026-07-27 10:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_goalprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goalaiplan',
            options={'verbose_name': 'Kế hoạch AI', 'verbose_name_plural': 'Kế hoạch AI'},
        ),
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Cột mốc', 'verbose_name_plural': 'Các cột mốc'},
        ),
        migrations.AlterField(
            model_name='goalaiplan',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Dễ'), ('medium', 'Trung bình'), ('hard', 'Khó')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='goalaiplan',
            name='recommended_hours_per_week',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goalprogress',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='goalprogress',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='goalprogress',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='goals.milestone'),
        ),
    ]
