# Generated by Django 6.0.7 on 2026-07-28 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_alter_goalaiplan_options_alter_milestone_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalaiplan',
            name='plan_data',
        ),
    ]
