# Generated by Django 6.0.7 on 2026-07-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_remove_goalaiplan_plan_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
