# Generated by Django 6.0.7 on 2026-08-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_alter_goalprogress_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
